# Generated by Django 4.1.2 on 2022-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_snippet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
